name: my first workflow

on:
   push:
    branches: [ "main"]

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Print welcome message
        run: echo "Hello, GitHub Actions CI/CD!"

      - name:  Run commands
        run: |
          echo "start app"
          echo "directory is $(pwd)"
          python3 --version

      - name: use custom environment variable
        env: 
          User_name: Student
        run: echo "Welcome $User_name"
          
